name: Release

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: yarn install

      - name: Build Dist Directory
        run: yarn run build

      - name: Run Release Script
        run: yarn run release # Adjust this command based on your release script
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
